[package]
name = "fixpoint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bump_alloc = { version = "0.1.0", path = "../bump_alloc" }
takyon = { version = "0.1.0", path = "../takyon" }
